const WHATSAPP="5492216102965"; const RATE=1565; let products=[];
const safe=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const waLink=name=>"https://wa.me/"+WHATSAPP+"?text="+encodeURIComponent("Hola Indio Informática, consulto por: "+name);
const CATEGORIES=[
{key:'Apple',title:'Apple',desc:'iPhone · iPad · Mac · Watch · AirPods',tag:'APPLE',icon:''},
{key:'Celulares',title:'Celulares',desc:'Samsung · Motorola · Xiaomi · Google',tag:'SMARTPHONES',icon:'01'},
{key:'Cámaras y Lentes',title:'Cámaras y Lentes',desc:'Nikon · Canon · Sony · Sigma · Tamron · Godox',tag:'FOTO & VIDEO',icon:'02'},
{key:'Notebooks',title:'Notebooks',desc:'Office · Estudio · Gaming',tag:'COMPUTACIÓN',icon:'03'},
{key:'Gaming',title:'Gaming',desc:'PlayStation · Xbox · Nintendo · Sim Racing',tag:'GAMING',icon:'04'},
{key:'Creator',title:'Creator',desc:'DJI · Insta360 · GoPro · Gimbals',tag:'CREATOR',icon:'05'},
{key:'Audio',title:'Audio',desc:'JBL · Auriculares · Parlantes',tag:'AUDIO',icon:'06'},
{key:'Tablets',title:'Tablets',desc:'Samsung · Lenovo y más',tag:'TABLETS',icon:'07'},
{key:'Accesorios',title:'Accesorios',desc:'Complementos para tus dispositivos',tag:'ACCESORIOS',icon:'08'}];
function renderCategories(){const g=document.querySelector('#categoryGrid');g.innerHTML=CATEGORIES.map(c=>`<button class="category-card category-${c.key.toLowerCase().replace(/[^a-z]+/g,'-')}" data-key="${safe(c.key)}"><div class="cat-top"><span>${c.tag}</span><i>${c.icon}</i></div><div><h3>${c.title}</h3><p>${c.desc}</p></div><div class="cat-bottom"><small>${products.filter(p=>p.category===c.key).length} productos</small><b>Explorar →</b></div></button>`).join('');g.querySelectorAll('.category-card').forEach(b=>b.addEventListener('click',()=>openCategory(b.dataset.key)))}
function openCategory(key){const c=CATEGORIES.find(x=>x.key===key);document.querySelector('#catalogo').hidden=false;document.querySelector('#categorias').hidden=true;document.querySelector('#catalogTitle').textContent=c.title;document.querySelector('#catalogEyebrow').textContent=c.tag;document.querySelector('#search').value='';renderSubcategories(key);apply(key);document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'})}
function renderSubcategories(key){const r=document.querySelector('#subcategoryRow');const subs=[...new Set(products.filter(p=>p.category===key).map(p=>p.brand).filter(Boolean))].sort();r.innerHTML='<button class="sub active" data-sub="">Todos</button>'+subs.map(s=>`<button class="sub" data-sub="${safe(s)}">${safe(s)}</button>`).join('');r.querySelectorAll('.sub').forEach(b=>b.onclick=()=>{r.querySelectorAll('.sub').forEach(x=>x.classList.remove('active'));b.classList.add('active');apply(key,b.dataset.sub)})}
function render(list){const g=document.querySelector('#productGrid');document.querySelector('#catalogCount').textContent=`${list.length} productos`;g.innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-image">${p.image?`<img src="${safe(p.image)}" alt="${safe(p.name)}" loading="lazy">`:`<div class="product-placeholder"><span>${safe(p.brand||p.category)}</span><strong>${safe(p.name)}</strong><small>Imagen oficial pendiente</small></div>`}</div><div class="product-info"><div class="product-brand">${safe(p.brand||p.category)}</div><div class="product-name">${safe(p.name)}</div>${p.description?`<p class="product-desc">${safe(p.description)}</p>`:''}<div class="product-price">${safe(p.price_display)}</div><div class="product-status">${safe(p.status)}</div><div class="product-actions"><button class="tech-btn" data-id="${safe(p.slug)}">Ver ficha técnica</button><a class="product-wa" href="${waLink(p.name)}" target="_blank" rel="noopener">WhatsApp →</a></div></div></article>`).join(''):'<div class="empty">No encontramos productos con esa búsqueda.</div>';g.querySelectorAll('.tech-btn').forEach(b=>b.onclick=()=>openTech(b.dataset.id))}
function apply(key,brand=''){const q=norm(document.querySelector('#search').value);let list=products.filter(p=>p.category===key);if(brand)list=list.filter(p=>p.brand===brand);if(q)list=list.filter(p=>norm(p.name+' '+p.brand+' '+p.description+' '+p.specs).includes(q));if(document.querySelector('#sort').value==='name')list.sort((a,b)=>a.name.localeCompare(b.name));render(list)}
function techFields(p){const n=p.name;const f=[];const add=(k,v)=>{if(v&&!f.some(x=>x[0]===k))f.push([k,v])}; add('Producto',n); if(p.brand)add('Marca',p.brand); const cap=n.match(/\b(\d+(?:[.,]\d+)?(?:GB|TB|MB))\b/ig); if(cap)add('Capacidad',cap.join(' · ')); const size=n.match(/\b(\d+(?:[.,]\d+)?(?:[”"']|\s?mm))\b/ig); if(size)add('Tamaño',size.join(' · ')); const focal=n.match(/\b\d+(?:-\d+)?mm\b/ig); if(focal)add('Distancia focal',focal.join(' · ')); const ap=n.match(/f\/?\d+(?:[.,]\d+)?(?:-\d+(?:[.,]\d+)?)?/ig); if(ap)add('Apertura',ap.join(' · ')); const hz=n.match(/\b\d+Hz\b/ig); if(hz)add('Frecuencia',hz.join(' · ')); const cpu=n.match(/(?:M[1-9](?: Pro| Max| Ultra)?|A\d+(?: Pro)?|Ryzen[^·/]+|Core (?:i[3579]|Ultra)[^·/]+|RTX \d{3,4})/i); if(cpu)add('Plataforma',cpu[0].trim()); if(/wifi/i.test(n))add('Conectividad','Wi‑Fi'); if(/cell/i.test(n))add('Conectividad','Wi‑Fi + Cellular'); if(/kit/i.test(n))add('Configuración','Kit'); if(/body/i.test(n))add('Configuración','Body'); if(p.description)add('Especificaciones disponibles',p.description); return f}
function openTech(id){const p=products.find(x=>x.slug===id);if(!p)return;document.querySelector('#techModal').classList.add('open');document.querySelector('#techContent').innerHTML=`<div class="tech-kicker">${safe(p.brand||p.category)}</div><h2>${safe(p.name)}</h2><div class="tech-price">${safe(p.price_display)}</div><div class="tech-grid">${techFields(p).map(x=>`<div><span>${safe(x[0])}</span><strong>${safe(x[1])}</strong></div>`).join('')}</div><div class="tech-block"><h3>Información</h3><p>Consultá disponibilidad, variantes y compatibilidad antes de realizar la compra. Te asesoramos por WhatsApp.</p></div><a class="btn dark tech-wa" href="${waLink(p.name)}" target="_blank">Consultar por WhatsApp →</a>`}
document.addEventListener('DOMContentLoaded',async()=>{products=await fetch('products.json').then(r=>r.json());renderCategories();const wa='https://wa.me/'+WHATSAPP;['waHeader','heroWa','waBtn','floatingWa'].forEach(id=>{const e=document.getElementById(id);if(e)e.href=wa});document.querySelector('#search').oninput=()=>{const k=document.querySelector('#catalogTitle').textContent;const c=CATEGORIES.find(x=>x.title===k);if(c)apply(c.key,document.querySelector('.sub.active')?.dataset.sub||'')};document.querySelector('#sort').onchange=()=>{const k=document.querySelector('#catalogTitle').textContent;const c=CATEGORIES.find(x=>x.title===k);if(c)apply(c.key,document.querySelector('.sub.active')?.dataset.sub||'')};document.querySelector('#backCategories').onclick=()=>{document.querySelector('#catalogo').hidden=true;document.querySelector('#categorias').hidden=false;document.querySelector('#categorias').scrollIntoView({behavior:'smooth'})};document.querySelector('#closeTech').onclick=()=>document.querySelector('#techModal').classList.remove('open');document.querySelector('#techModal').onclick=e=>{if(e.target.id==='techModal')e.currentTarget.classList.remove('open')}});
